added more docs to readme
vincenzopalazzo/cln4go pull request #21
Opened 2022-08-02 07:46 UTC by gabbyprecious

2022-08-02 08:44 UTC, vincenzopalazzo reviewed
I would like to follow the following the rust repository https://github.com/laanwj/rust-clightning-rpc for the Readme

2022-08-02 08:47 UTC, gabbyprecious commented
Alright will work on that. with the hacking.md guideline?

2022-08-16 20:23 UTC, vincenzopalazzo requested changes
Thanks! looks Very good! 

I found some errors related to the package naming, and some typos maybe you can also open a PR when you have time to fix the typo in the repo where these examples was.

Thanks!

2022-08-16 20:23 UTC, vincenzopalazzo commented on README.md
> +  <h1>Cln4go</h1>
```suggestion
  <h1>cln4go</h1>
```

2022-08-16 20:23 UTC, vincenzopalazzo commented on README.md
> +| cln4go-plugin |    Package that provides a plugin API to give the possibility to implement a plugin in Go     |
```suggestion
| cln4go-plugin |    Package that provides a plugin API to give the possibility to implement a plugin in Go     | 
| cln4go-common |    Package that provides common interface for the monorepo. Go     | 
```

2022-08-16 20:23 UTC, vincenzopalazzo commented on docs/MAINTAINERS.md
> +- **plugin**: Changes related to the plugin library
```suggestion
- **plugin**: Changes related to the plugin module
- **common**: Changes related to the common module.
```

2022-08-16 20:23 UTC, vincenzopalazzo commented on docs/MAINTAINERS.md
> +    - `make {changelog_rpc|changelog_plugin|changelog_plugin_macros|changelog_common|changelog}`, where`make {changelog_client|changelog_flutter|changelog}`, where
```suggestion
    - `make {changelog_rpc|changelog_plugin|changelog_common|changelog}`, where`:
```

2022-08-16 20:23 UTC, vincenzopalazzo commented on docs/MAINTAINERS.md
> +        - `changelog_plugin`: generate the changelog for plugin library;
```suggestion
        - `changelog_plugin`: generate the changelog for plugin module;
        - `changelog_plugin_macros`: generate the changelog for common module.
```

2022-08-16 20:57 UTC, vincenzopalazzo requested changes
Just another format change

2022-08-16 20:57 UTC, vincenzopalazzo commented on docs/MAINTAINERS.md
> +    - - `make {changelog_rpc|changelog_plugin|changelog_common|changelog}`, where`:changelog_common|changelog}`, where`make {changelog_client|changelog_flutter|changelog}`, where
```suggestion
    - `make {changelog_rpc|changelog_plugin|changelog_common|changelog}`, where:
```

2022-08-18 12:38 UTC, vincenzopalazzo approved these changes

2022-08-18 12:38 UTC, merged